# Generated by Django 4.0.4 on 2022-05-28 16:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Start point"
                    ),
                ),
                (
                    "end",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="End point"
                    ),
                ),
                ("length", models.FloatField(verbose_name="Length")),
            ],
        ),
        migrations.CreateModel(
            name="SpeedReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_speed",
                    models.FloatField(verbose_name="Average Speed (km/h)"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "road_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_readings",
                        to="roads.roadsegment",
                        verbose_name="Road Segment",
                    ),
                ),
            ],
        ),
    ]
