# Generated by Django 4.0.4 on 2022-05-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_auto_20220528_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roadsegment',
            unique_together={('start', 'end', 'length')},
        ),
    ]
