# Generated by Django 4.0.4 on 2022-05-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_alter_roadsegment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadsegment',
            options={'ordering': ['speed_readings__timestamp']},
        ),
    ]
