# Generated by Django 4.0.4 on 2022-05-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_alter_roadsegment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadsegment',
            options={'ordering': ['-speed_readings__timestamp']},
        ),
        migrations.AlterModelOptions(
            name='speedreading',
            options={'ordering': ['-timestamp']},
        ),
    ]
